# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lfS6o2RtuuAV1ok7hgE2Upa0Z44_oFaH
"""

# =====================================================
# CRYPTOCHAIN — STREAMLIT
# =====================================================

import streamlit as st
import sympy as sp
import random

# =====================================================
# CONFIGURAÇÃO
# =====================================================

st.set_page_config(
    page_title="CryptoChain",
    page_icon="🔐",
    layout="centered"
)

# =====================================================
# ESTILO CYBERPUNK AZUL
# =====================================================

st.markdown("""
<style>

.stApp {
    background-color: #001133;
    color: #00BFFF;
}

h1, h2, h3, h4 {
    color: #00BFFF;
}

.stButton>button {
    background-color: #001133;
    color: #00BFFF;
    border: 1px solid #00BFFF;
    border-radius: 10px;
}

.stTextInput>div>div>input {
    background-color: #001133;
    color: #00BFFF;
}

.stTextInput label {
    color: #00BFFF !important;
    font-weight: bold;
}

</style>
""", unsafe_allow_html=True)


resposta = st.text_input("", label_visibility="collapsed")

# =====================================================
# SESSION STATE
# =====================================================

if "fase" not in st.session_state:
    st.session_state.fase = 1

if "pontos" not in st.session_state:
    st.session_state.pontos = 0

if "vidas" not in st.session_state:
    st.session_state.vidas = 5

if "fase_liberada" not in st.session_state:
    st.session_state.fase_liberada = False
    
def reiniciar_jogo():
    st.session_state.fase = 1
    st.session_state.pontos = 0
    st.session_state.vidas = 5
    st.session_state.fase_liberada = False

# =====================================================
# HASH FICTÍCIO
# =====================================================

def gerar_hash():

    caracteres = "ABCDEF0123456789"

    return "".join(
        random.choice(caracteres)
        for _ in range(12)
    )

# =====================================================
# FASES
# =====================================================

fases = {

    1: {
        "nome": "BLOCO GÊNESIS",

        "historia":
            "O primeiro bloco da blockchain foi "
            "parcialmente corrompido durante um ataque.",

        "desafio":
            "59 mod 11",

        "resposta": 4,

        "missao":
            "Descubra o resto correto da divisão para "
            "restaurar o Bloco Gênesis.",

        "pontos": 100
    },

    2: {
        "nome": "VALIDAÇÃO DE TRANSAÇÕES",

        "historia":
            "Milhares de transações chegaram ao servidor principal.",

        "desafio":
            "239 mod 13",

        "resposta": 5,

        "missao":
            "Calcule corretamente o identificador modular para "
            "validar as transações pendentes.",

        "pontos": 150
    },

    3: {
        "nome": "HASH REDUZIDO",

        "historia":
            "O hash original foi reduzido usando congruência modular.",

        "desafio":
            r"94 \equiv ? \pmod{17}",
        "resposta": 9,

        "missao":
            "Encontre o representante correto para recuperar o hash.",

        "pontos": 200
    },

    4: {
        "nome": "CONSENSO DA REDE",

        "historia":
            "Dois nós da blockchain discordam sobre um bloco.",

        "desafio": r"145 \equiv 28 \pmod{13}",

        "tipo": "bool",

        "resposta": "Sim",

        "missao":
            "Verifique se ambos os nós realmente armazenam o mesmo bloco.",

        "pontos": 250
    },

    5: {
        "nome": "CHAVE PÚBLICA",

        "historia":
            "A chave pública armazenada está reduzida módulo 9.",

        "desafio": r"x \equiv 38 \pmod{9}",

        "resposta": 2,

        "missao":
            "Descubra o menor representante positivo da chave pública.",

        "pontos": 350
    },

    6: {
        "nome": "AGRUPAMENTO DE BLOCOS",

        "historia":
            "Dois blocos foram unidos durante a sincronização da rede.",

        "desafio": r"(47+86)\bmod17",

        "resposta": 14,

        "missao":
            "Calcule a soma modular para sincronizar corretamente os blocos.",

        "pontos": 450
    },

    7: {
        "nome": "CONTRATO INTELIGENTE",

        "historia":
            "Um contrato inteligente executou uma multiplicação modular.",

        "desafio": r"19\times37\bmod23",

        "resposta": 13,

        "missao":
            "Determine o resultado da multiplicação modular para confirmar o contrato.",

        "pontos": 600
    },

    8: {
        "nome": "NONCE DO MINERADOR",

        "historia":
            "O minerador encontrou um possível nonce.",

        "desafio": r"7^{8}\bmod13",
        
        "resposta": 3,

        "missao":
            "Use potenciação modular para validar o nonce encontrado.",

        "pontos": 800
    },

    9: {
        "nome": "ASSINATURA DIGITAL",

        "historia":
            "Uma assinatura digital utiliza exponenciação modular.",

       "desafio": r"11^{20}\bmod12",

        "resposta": 1,

        "missao":
            "Calcule corretamente a exponenciação modular para autenticar a assinatura.",

        "pontos": 1000
    },

    10: {
        "nome": "RESTAURAÇÃO DA BLOCKCHAIN",

        "historia":
            "O último bloco da blockchain foi localizado.",

        "desafio": r"(9^{12}+14\cdot31)\bmod19",

        "resposta": 4,

        "missao":
            "Resolva o desafio criptográfico final para restaurar definitivamente a blockchain.",

        "pontos": 1500
    }
}

# =====================================================
# SIDEBAR
# =====================================================

st.sidebar.title("🔐 STATUS")

st.sidebar.metric(
    "💎 Pontos",
    st.session_state.pontos
)

st.sidebar.metric(
    "🛡️ Chaves",
    st.session_state.vidas
)

blocos = "🟦" * (st.session_state.fase - 1)
blocos += "⬜" * (10 - (st.session_state.fase - 1))

st.sidebar.markdown("### 🔗 Blockchain")
st.sidebar.markdown(blocos)

st.sidebar.markdown("### 💾 Hash Atual")
st.sidebar.code(gerar_hash())

st.sidebar.progress(
    min(st.session_state.fase, 10) / 10
)

if st.sidebar.button("🔄 Reiniciar jogo"):
    reiniciar_jogo()
    st.rerun()
    
# =====================================================
# GAME OVER
# =====================================================

if st.session_state.vidas <= 0:

    st.error("☠️ CHAVES COMPROMETIDAS")
    st.stop()

# =====================================================
# FINAL
# =====================================================

if st.session_state.fase > 10:

    st.success("👑 BLOCKCHAIN RESTAURADA")

    st.balloons()

    st.write(
        f"Pontuação Final: {st.session_state.pontos}"
    )

    if st.session_state.pontos >= 5000:

        st.success(
            "🏆 RANK S — CRIPTÓGRAFO MESTRE"
        )

    elif st.session_state.pontos >= 3000:

        st.success(
            "🥇 RANK A — ANALISTA BLOCKCHAIN"
        )

    else:

        st.success(
            "🥈 RANK B — OPERADOR DE SEGURANÇA"
        )
        
    if st.button("🔄 Jogar novamente"):
        reiniciar_jogo()
        st.rerun()
        
    st.stop()

# =====================================================
# FASE ATUAL
# =====================================================

fase = fases[st.session_state.fase]

st.title("🔐 CryptoChain")

st.subheader(
    f"🔗 BLOCO {st.session_state.fase}/10 — {fase['nome']}"
)

st.write(fase["historia"])

st.markdown("### 💻 Desafio")

st.latex(fase["desafio"])

st.info(f"🎯 Missão: {fase['missao']}")

# =====================================================
# INPUT
# =====================================================

if fase.get("tipo") == "bool":

    resposta = st.radio(
        "Sua resposta:",
        ["Sim", "Não"]
    )

else:

    resposta = st.text_input(
        "Digite sua resposta:"
    )

# =====================================================
# ENVIAR
# =====================================================

if not st.session_state.fase_liberada:

    if st.button("Enviar"):

        try:

            if fase.get("tipo") == "bool":

                correto = (
                    resposta
                    == fase["resposta"]
                )

            else:

                valor = int(
                    sp.sympify(
                        resposta.replace("^", "**")
                    )
                )

                correto = (
                    valor
                    == fase["resposta"]
                )

            if correto:

                st.success(
                    "✅ BLOCO VALIDADO"
                )

                st.session_state.pontos += (
                    fase["pontos"]
                )

                st.session_state.fase_liberada = True

            else:

                st.error(
                    "❌ HASH INVÁLIDO"
                )

                st.session_state.vidas -= 1

        except:

            st.warning(
                "⚠️ Entrada inválida."
            )

# =====================================================
# PRÓXIMA FASE
# =====================================================

if st.session_state.fase_liberada:

    if st.button("🚀 Próxima Fase"):

        st.session_state.fase += 1

        st.session_state.fase_liberada = False

        st.rerun()
